export const QUERY_KEYS = {
  WAITERS: "WAITERS",
  WAITERS_MUTATION: "WAITERS_MUTATION",

  FOODS: "FOODS",
  FOODS_MUTATION: "FOODS_MUTATION",

  ORDERS: "ORDERS",
  ORDERS_MUTATION: "ORDERS_MUTATION",

  COMPANY_INFO: "COMPANY_INFO",
};
